-- A small integer name for every card, so the price tables can stop repeating the long one.
--
-- price_point is 2.8 million rows and its primary key leads with card_id, a text column
-- averaging about twelve bytes. That text is carried twice over -- once in the row and once
-- in every index entry -- and measured against a real sample of 400,000 rows it costs 9.1
-- bytes per row more than an integer would: roughly 26 MB across the table, on a database
-- with a 500 MB ceiling.
--
-- tcg_cards keeps its text id. That id is the one the catalogue publishes, the one the app
-- passes around and the one a person can read; replacing it would ripple through every
-- query for no gain, because the catalogue is 20,635 rows and its size is not the problem.
-- This is a second name used only where the repetition is expensive.
--
-- `generated by default as identity` rather than a plain integer: existing rows are numbered
-- when the column is added, and a card imported later gets its own number without the
-- importer having to know this column exists.
alter table public.tcg_cards
  add column if not exists ref integer generated by default as identity;

-- A foreign key needs something unique to point at.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'tcg_cards_ref_unique'
  ) then
    alter table public.tcg_cards add constraint tcg_cards_ref_unique unique (ref);
  end if;
end $$;

-- Translating between the two names happens on every price read, so it needs to be an
-- index lookup rather than a scan of 20,635 rows.
create index if not exists tcg_cards_id_ref_idx on public.tcg_cards (id) include (ref);
